---
title: "ggplot"
output: html_notebook
---

```{r}
# library

library(tidyverse)
```

```{r}
# data

revenue_breakdown <- CodeClanData::qb_revenue_breakdown
monthly_sales <- CodeClanData::qb_monthly_sales
competitors <- CodeClanData::qb_competitors
device_data <- CodeClanData::qb_device_data
```

1.

```{r}
ggplot(revenue_breakdown)+
  aes(x = Year, y = Revenue, group = Product, fill = Product)+
  geom_bar(stat = "identity")+ # geom_col()
  labs(title = "Sources of revenue across two years\n",
       x = "\nYear",
       y = "Revenue\n")+
  theme_bw(base_size = 12)+
  scale_fill_manual(values = c("Accessories" = "#E89FE9",
                               "Smart Watches" = "#B6A7B5",
                               "Subscription Services" = "#50434F",
                               "Trackers" = "#F9A472"))
```
2. 

```{r}
kwikbit_sales <- monthly_sales %>% 
  filter(Cashflow == "Kwikbit Unit 1 Sales") #%>% 
  #mutate(Cashflow = recode(Cashflow, "Kwikbit Unit 1 Sales" = "KwikBit Unit 1"))

ggplot(kwikbit_sales)+
  aes(x = Date, y = Amount)+
  geom_line(color = "#E89FE9")+
  labs(title = "Monthly sales for flagship product",
       x = "Period")+
  theme_bw(base_size = 12)
```
3.

```{r}
revenue_cost <- monthly_sales %>% 
  filter(Cashflow %in% c("Total Revenue", "Cost"))

ggplot(revenue_cost)+
  aes(x = Date, y = Amount, colour = Cashflow)+
  geom_line()+
  scale_y_continuous(limits = c(1500, 3000))+
  labs(title = "Monthly revenue and costs over the last year",
       x = "Period")+
  theme_bw(base_size = 12)+
  scale_colour_manual(values = c("Cost" = "#E89FE9",
                               "Total Revenue" = "#F9A472"))
```

4. 

```{r}
competitors1 <- competitors %>% 
  mutate(Revenue = Revenue/1000000)

ggplot(competitors1)+
  aes(x = Year, y = Revenue, group = Company, fill = Company)+
  geom_area()+
  labs(title = "Competitors' annual sales of personal fitness trackers\n",
       x = "\nYear",
       y = "Revenue (million units)\n")+
  theme_bw(base_size = 12)+
  scale_fill_manual(values = c("Competitor 1" = "#E89FE9",
                               "Competitor 2" = "#B6A7B5",
                               "Competitor 3" = "#50434F",
                               "Competitor 4" = "#F9A472"))
```
5.

```{r}
ggplot(competitors)+
  aes(x = Year, y = Revenue, group = Company, colour = Company)+
  geom_line()+
  geom_point()+
  labs(title = "Sales of four competitors over the past 5 years\n",
       x = "\nYear",
       y = "Revenue (million units)\n")+
  theme_bw(base_size = 12)+
  scale_colour_manual(values = c("Competitor 1" = "#E89FE9",
                               "Competitor 2" = "#B6A7B5",
                               "Competitor 3" = "#50434F",
                               "Competitor 4" = "#F9A472"))
```

6.

```{r}
device_data <- 
mutate(device_data, hour = hours + (mins/60))

ggplot(device_data) +
  aes(x = hour, y = counts, colour = device) +
  geom_line(show.legend = FALSE) + 
  scale_x_continuous("Time (hours)") +
  scale_y_continuous("Steps") +
  facet_grid(id ~ device) +
  scale_colour_manual(values = c("#E89FE9", "#B6A7B5", "#50434F", "#F9A472")) +
  theme_bw(base_size = 12)+
  ggtitle("Our device vs. competitors for 5 individuals")
  
```



