---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
drink_menu <- read.csv("data/starbucks_drinkMenu_expanded.csv")
```

```{r}
# variable names
names(drink_menu)

# dimensions
dim(drink_menu)

head(drink_menu, 10)

tail(drink_menu, 5)
```

```{r}
drink_menu %>%
  select(Beverage_category, Beverage, Beverage_prep, Calories) %>% #select variables
  filter(is.na(Calories)) %>% #check if there are any NA values in the Calories
  summarise(count_of_missing_calories = n())
```
```{r}
drinks_calories <- drink_menu %>%
  mutate(calorie_diff = 135 - Calories) #create new column 
drinks_calories
```

```{r}
calories_by_category <- drinks_calories %>%
  group_by(Beverage_category) %>%
  summarise(mean_calories = mean(Calories))

calories_by_category
```
```{r}
most_calories <- calories_by_category %>% 
  arrange(desc(mean_calories)) %>%
  head(3)

most_calories
```
```{r}
least_calories <- calories_by_category %>% 
  arrange(mean_calories) %>%
  head(3)

least_calories
```

```{r}
average_bev_prep <- drink_menu %>% 
  group_by(Beverage_prep) %>% 
  summarise(average_cal = mean(Calories)) %>% 
  arrange(desc(average_cal))

average_bev_prep  
```


```{r}
ave_calories <- drinks_calories %>% 
  summarise(mean_calories_value = mean(Calories)) %>% 
  pull()

ave_calories

above_average_cal_drinks <- average_bev_prep %>% 
  group_by(Beverage_prep) %>% 
  filter(average_cal >= ave_calories)

above_average_cal_drinks

# or
average_bev_prep %>% 
  mutate(is_greater_than_average = average_cal >= ave_calories) %>% 
  filter(is_greater_than_average == T)
```

Which is the best type of coffee drink (and by ‘drink’ we mean the combination of Beverage_category, Beverage and Beverage_prep) to get if you’re worried about consuming too many calories?
```{r}
head(drinks_calories)
```
```{r}
# find coffee with lowest calories:

drinks_calories %>% 
  group_by(Beverage_category, Beverage, Beverage_prep) %>% 
  #summarise(min_cal = min(Calories)) %>% 
  arrange(Calories) %>% 
  head(1)
```

```{r}
drinks_calories %>% 
  filter(Beverage_category != "Tazo® Tea Drinks") %>% 
  group_by(Beverage_category, Beverage, Beverage_prep) %>% 
  summarise(min_cal = min(Calories)) %>% 
  arrange(min_cal) %>% 
  head(1)
```


