---
title: "SQL & Programming"
output: html_notebook
---
3.
```{r}
source("~/acme_credentials.R")
```

```{r}
library(RPostgres)
library(tidyverse)
```

```{r}
db_connection = dbConnect(
  drv = Postgres(), 
  user = acme_username,
  password = acme_password,
  dbname = acme_database,
  host = acme_host,
  port = acme_port,
  bigint = "numeric"
)
```

```{r}
rm(acme_database, acme_host, acme_password, acme_port, acme_username)
```

```{r}
dbListTables(conn = db_connection)
```

```{r}
dbListFields(conn = db_connection, name = "employees")
```

4. 
```{sql, connection = db_connection}
SELECT 
  id,
  CONCAT(first_name,' ' ,last_name) AS full_name,
  email,
  team_id
FROM employees
```
5.
```{sql, connection = db_connection}
SELECT 
  id,
  first_name,
  last_name,
  email,
  team_id AS team_name
FROM employees
```
6. 
```{sql, connection = db_connection}
SELECT
  team_id,
  COUNT(id) AS num_employees
FROM employees
GROUP BY team_id
```
7.
```{sql, connection = db_connection}
SELECT *
FROM employees
WHERE email NOT LIKE '%@%' OR email IS NULL
```
```{sql, connection = db_connection}
SELECT * FROM feedbacks
```
9.
```{sql, connection = db_connection}
SELECT
  e.id,
  e.first_name,
  e.last_name,
  f.date
FROM employees AS e INNER JOIN feedbacks AS f
ON e.id = f.employee_id
ORDER BY date DESC
```
10.
```{sql, connection = db_connection}
SELECT
  t.name,
  COUNT(e.id) AS num_employees
FROM employees AS e INNER JOIN teams AS t
ON e.team_id = t.id
WHERE e.first_name LIKE '_'
GROUP BY t.name
ORDER BY COUNT(e.id) DESC
LIMIT 1
```

```{r}
feedbacks_table <- dbGetQuery(conn = db_connection, statement = "SELECT * FROM feedbacks")
```

11.
```{r}
review <- as.character(feedbacks_table$message)

review <- str_to_lower(review)
review <- str_remove_all(review, "[\\.,!?]")
review <- str_replace_all(review, "-", " ")
review <- str_squish(review)
review <- str_trim(review)
review <- str_split(review, " ")
review <- str_remove_all(review, "[\\\]")
review <- flatten_chr(review)
review

positive_words <- c("great", "good", "happy", "content", "fulfilled", "fulfilling", "positive", "positives", "cheerful", "nice", "ambition", "ambitions", "ambitious", "progress", "joy", "fast", "achieve", "achieving", "achievements", "best", "better",  "unlimited", "pros", "competitive", "opportunity", "advancement", "friendly", "smart", "interesting", "challenging", "grow", "caring", "balance", "helpful", "advantage", "learning", "ethical", "responsible", "responsibilities")

negative_words <- c("worse", "worsening", "worst", "slow", "sluggish", "impatient", "unfulfilled", "unfulfilling", "negative", "bad", "limited", "limit", "limitations", "cons", "frustrated", "frustrating", "frustration", "dull", "boring", "politics", "political", "ignore", "ignored", "ignoring", "sad", "depressed", "depressing", "nasty", "stress", "stresses", "stressed", "stressful", "horrid", "horrible", "terrible", "deadline", "deadlines", "uncaring", "remote", "difficult", "difficulties", "bully", "bullying")


searching_feedback <- function(x) {
  score <- 0
  
  for (word in x){
    if (word %in% positive_words){
      score = score + 1
    } else if (word %in% negative_words) {
      score = score - 1
    }
  }
  return(score)
}
searching_feedback(review)
```

```{r}
#dbDisconnect(conn = db_connection)
```

