---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)

movies <- read.csv("archive/tmdb_5000_movies.csv")
```
```{r}
head(movies)

names(movies)
```

# 1
First thoughts
- homepage - missing values
- revenue - 0 value
- few factor types

# 2

```{r}
movies_selected <-movies %>% 
  select(title,runtime, budget)
movies_selected
```

# 3

```{r}
# count the number of missing values in each column
# functional programming
movies_selected %>% 
  summarise(across(.fns = ~sum(is.na(.x))))
```

```{r}
movies_selected %>% 
  summarise(na_runtime = sum(is.na(runtime)),
            na_title = sum(is.na(title)),
            na_budget = sum(is.na(budget)))
```


# 4

```{r}
# converts runtimes 0 into NAs

movies_runtime <- movies_selected %>%
  mutate(runtime = na_if(runtime, 0))

# counts missing values in column runtime

movies_runtime %>% 
  summarise(count_missing = sum(is.na(runtime)))
```

# 5

```{r}
# represent the missing values in runtime with the median runtime 

movies_imputed <- movies_runtime %>% 
  mutate(runtime = coalesce(runtime, median(runtime, na.rm = TRUE)))

```
```{r}
movies_imputed %>% 
  summarise(count_missing = sum(is.na(runtime)))
```

# 6 

```{r}
# gets the movies with the longest runtimes

movies_imputed %>% 
  slice_max(runtime, n = 10)
```
```{r}
# # gets the movies with the shortest runtimes

movies_imputed %>% 
  slice_min(runtime, n = 10)
```

# 7

```{r}
# Overwrites movies_imputed to contain new budget values

movies_imputed <- movies_imputed %>%
  mutate(budget = if_else(budget < 100, median(budget), budget))
```


# Extension 1

```{r}
movie_budgets <- movies_imputed %>% 
  mutate(budget_type = case_when(budget < 12e6 ~ "Small budget",
                                 budget < 40e6 ~ "Meium budget", #Budgets between 12 and 40 million as ‘Medium budget’
                                 #budget > 12e6 & budget < 40e6 ~ "Medium budget",
                                 budget >= 40e6 ~ "Big budget"))
movie_budgets
```
# 2
```{r}
# summarises the number of missing values cross all columns of type numeric

movies %>%
  summarise(across(where(is.numeric), ~sum(is.na(.x))))
```


```{r}
# summarises the number of missing values cross all columns of type character

movies %>%
  summarise(across(where(is.character), ~sum(is.na(.x))))