---
title: "Tivyverse"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
rtweets <- read.csv("data/code_clan_tweets.csv")
codeclan_info <- read_csv("data/code_clan_info.csv")

names(rtweets)
nrow(rtweets)
ncol(rtweets)
```

```{r}
# count total number of favourite tweets, don't include tweets that are quoted

rtweets %>% 
  filter(is_quote == FALSE) %>% 
  summarise(total = sum(favorite_count))
```

```{r}
# summarise the mean number of retweets by source

rtweets %>%
  filter(is_quote == FALSE) %>% # omit quoted tweets
  group_by(source) %>% # split by the type
  summarise(average_retweet = mean(retweet_count))
```

```{r}
# count the number of likes by media type, and arrange them from most likes to least 
# Assume that any tweets without a listed media type are of type “text”

rtweets %>% 
  mutate(media_type2 = replace_na(media_type, "text")) %>% 
  group_by(media_type2) %>% 
  summarise(favorite_count_total = sum(favorite_count)) %>% 
  arrange(desc(favorite_count_total))
```

```{r}
# find the mean number of characters a tweet contains

rtweets %>% 
  summarise(avg_tweet_length = mean(display_text_width))
```

```{r}
# alternative way of testing the str_length function

code_clan_tweets_text <- rtweets %>%
  mutate(count_str_length = str_length(text)) %>%
  select(count_str_length, display_text_width)
```


```{r}
# join it to the code_clan_tweets tibble, so that you have a status_url for each tweet

codeclan_all <- left_join(rtweets, codeclan_info, by = "tweet_id")
```

```{r}
# create a variable which has all the hashtags in lowercase for analysis

codeclan_hashtags <- codeclan_all%>% 
  select(tweet_id, hashtags) %>%
  mutate(lowcase_hashtag = str_to_lower(hashtags)) %>%
  select(-hashtags) %>%
  drop_na(lowcase_hashtag)

head(codeclan_hashtags)
```

```{r}
# use the str_sub function to get tweets with more than one hashtag (get the first 2 letters of each tweet)

hashtags_multiple <- codeclan_hashtags %>% 
  mutate(first_letters = str_sub(lowcase_hashtag, 1, 2)) %>%
  filter(str_detect(first_letters, "c\\("))

hashtags_multiple
```

```{r}
# find all cases where a tweet text mentions edinburgh, and count in how many tweets it appears

rtweets %>% 
  select(text) %>% 
  mutate(lower_case_text = str_to_lower(text)) %>% 
  filter(str_detect(lower_case_text, "edinburgh")) %>% 
  summarise(edi_mentioned = n())
  
```

```{r}
# use str_extract_all and regex to find usernames tweeted by CodeClan

user_pattern <- "@[a-zA-Z0-9_]+"
tweets <- rtweets %>% 
  select(text)
head(str_extract_all(tweets$text, user_pattern))
```


