---
title: "Cleaning & Extra dplyr"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
```

```{r}
# read in data using read_csv tidyverse's package version

books <- read_csv("data/books.csv")
```

```{r}
# clean column names
# assigned to new variable

all_books <- clean_names(books)

all_books <- all_books %>% 
  rename(isbn_13 = isbn13)
```

# Checking Data

```{r}
nrow(all_books)

ncol(all_books)

dim(all_books)

names(all_books)

# preview first 10 rows

head(all_books, 10)

tail(all_books, 10)

glimpse(all_books)

# view data in table format

view(all_books)

all_books

# how many missing values
sum(is.na(all_books))
```

```{r}
# an overview of missing values

all_books %>% 
  summarise(across(.fns = ~sum(is.na(.x))))
```
```{r}
# how many distinct language codes
all_books %>% 
  distinct(language_code) %>% 
  nrow()
```
```{r}
# how many distinct publishers
all_books %>% 
  distinct(publisher) %>% 
  nrow()
```

```{r}
# how many distinct authors
all_books %>% 
  distinct(authors) %>% 
  nrow()
```


```{r}
all_books %>% 
  select(book_id, title, num_pages) %>% 
  filter(num_pages == 0) %>% 
  summarise(zero_pages = n())
```
```{r}
# sums number of num_pages with value 0
all_books %>% 
  filter(num_pages %in% 0) %>% 
  summarise(count = n())
```

```{r}
clean_books <- all_books %>%
  mutate(num_pages = na_if(num_pages, 0),
         average_rating = na_if(average_rating, 0.00),
         isbn = na_if(isbn, "0.00"),
         publication_date = na_if(publication_date, "0"),
         publication_date = as.Date(publication_date, "%m/%d/%Y"),
         publication_year = format(publication_date, "%Y"))
clean_books
```
```{r}
clean_books %>% 
   summarise(na_pages = sum(is.na(num_pages)),
            na_rating = sum(is.na(average_rating)),
            na_isbn = sum(is.na(isbn)),
            na_pub_date = sum(is.na(publication_date)))
```

# Findings

* Highest number of published books was in 2006 at number 1324.
```{r}
clean_books %>% 
  select(publication_year) %>% 
  group_by(publication_year) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count))
```
* Average book rating was 3.95.
```{r}
ave_book_rating <- clean_books %>% 
  summarise(mean_rating = mean(average_rating, na.rm = T)) %>% 
  pull()
```

```{r}
best_rated_books <- clean_books %>% 
  filter(average_rating > ave_book_rating)
```

```{r}
best_rated_books %>% 
  select(average_rating, ratings_count, title) %>% 
  #arrange(desc(average_rating))
  group_by(average_rating,ratings_count) 
```


```{r}
# these two books have observations under incorrect columns

clean_books %>% 
  filter(language_code == "9780674842113" | language_code == "9780851742717") 
```

```{r}
all_books %>% 
  select(publisher) %>% 
  group_by(publisher) %>% 
  summarise(publisher_count = n())
```

```{r}
all_books %>% 
  select(authors) %>% 
  group_by(authors) %>% 
  summarise(authors_count = n()) %>% 
  arrange(desc(authors_count))
```

```{r}
# oldest book

all_books %>% 
  select(title, publication_date) %>% 
  arrange(publication_date) %>% 
  head(2)
```
```{r}
# most recent book
all_books %>% 
  select(title, publication_date) %>% 
  arrange(desc(publication_date)) %>% 
  head(1)
```

```{r}
all_books %>% 
  select(language_code) %>%
  group_by(language_code) %>% 
  summarise(languages_count = n()) #%>% 
  #arrange(desc(languages_count))
```

```{r}
# book with most text reviews is The Giver with 56604 reviews

clean_books %>% 
  slice_max(text_reviews_count)
```
```{r}
# book with most ratings is The Hobbit with 2530894	ratings
clean_books %>% 
  slice_max(ratings_count)
```
```{r}
# Vintage published most books 255
clean_books %>% 
  group_by(publisher) %>% 
  summarise(n_titles = n()) %>% 
  arrange(desc(n_titles))
```

```{r}
# if two Penguins combined they published most books

penguin_names <- c("Penguin Books", "Penguin Classics")

clean_books %>% 
  filter(publisher %in% penguin_names) %>%
  nrow()
```

```{r}
# longest book in each language

eng_codes <- c("en-CA", "en-GB", "en-US", "eng")

clean_books %>% 
  mutate(language_code = if_else(language_code %in% eng_codes, "eng", language_code)) %>% # recoding
  group_by(language_code) %>% 
  slice_max(num_pages) %>% 
  select(language_code, num_pages) %>% 
  arrange(desc(num_pages))
```
```{r}
# author Chaucer published books in 'enm' Middle English language as only author in our dataset
books %>% 
  filter(language_code == "enm")
```

