---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
```

```{r}
card_base <- read_csv("data/CardBase.csv")
customer_base <- read_csv("data/CustomerBase.csv")
fraud_base <- read_csv("data/FraudBase.csv")
transaction_base <- read_csv("data/TransactionBase.csv") # %>%  clean_names()
```

```{r}
card_base <- clean_names(card_base)
customer_base <- clean_names(customer_base)
fraud_base <- clean_names(fraud_base)
transaction_base <- clean_names(transaction_base)
```


```{r}
left_join(card_base, customer_base, by = "cust_id")
```
```{r}
fraud_transaction <- full_join(fraud_base,transaction_base, by = "transaction_id")
nrow(fraud_transaction)
nrow(fraud_base) #109 fraud_base
nrow(transaction_base) # 1000 
```

```{r}

semi_join(card_base, transaction_base, by = c("card_number" = "credit_card_id"))

```

```{r}
card_custumer <- left_join(card_base, customer_base, by = "cust_id") %>% view
card_customer_transaction <- left_join(card_custumer, transaction_base, by = c("card_number" = "credit_card_id")) %>% view
card_cust_transaction_fraud <- right_join(card_customer_transaction, fraud_base, by = "transaction_id") %>% view

# easier approach
card_base %>% 
  inner_join(customer_base, by = "cust_id") %>% 
  inner_join(transaction_base, by = c("card_number" = "credit_card_id")) %>% 
  inner_join(fraud_base, by = "transaction_id") %>% view
  
```



