---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
hat_observations <- read_csv("data/hat_observations.csv")
exam_scores <- read_csv("data/exam_scores.csv")
```

```{r}
tidy_hat_observations <-
  hat_observations %>%
  separate(observation,
           c("hat_colour", "hat_type"),
           sep = ",")
```

```{r}
# initial approach:
tidy_hat_observations %>% 
  unite(date, c("day","month","year"), sep = "/") %>% # unites columns
  filter(hat_type == "beret") %>% 
  arrange(desc(observation_count)) # finds date where the most beret where observed
  
# correct approach
tidy_hat_observations %>% 
  unite("date", day:year, sep = "/") %>% 
  filter(hat_type == "beret") %>% 
  group_by(date) %>% 
  summarise(total = sum(observation_count)) %>% 
  slice_max(total)
```

```{r}
exam_scores %>% 
  pivot_longer(cols = c(exam_Q1:exam_Q10),
               names_to = "exam_question",
               values_to = "score") %>% 
  separate(exam_question, c("exam", "num_of_question"), sep = "Q") %>% 
  select(-exam)


```

