---
title: "1.2 Hypothesis testing - interpretation"
output: html_notebook
---
------------------------------
1.2.1 Defining the Hypothesis
------------------------------

# 1.
You work for a independent coffee shop. The boss tells you that she thinks that around 40% of people in the town (population 30,000) know of the coffee shop, but you are skeptical of the estimate. You conduct a random survey of 200 people in the town, asking if respondents are aware of your coffee shop. You want to use the sample to test the hypothesis that 40% or more of the town’s population have heard of the coffee shop.
-->
Population = 30,000
Sample = 200

If we are calculating proportion we need to have a categorical variable with two levels
(aware_of_coffee_shop, not_aware_of_coffee_shop).

We calculate the statistic we are interested in from the current sample. In the present case we calculate number of people who heard off coffee shop divided by the total number of participants in the current sample.

H0: π aware_of_coffee_shop = 0
Ha: π aware_of_coffee_shop > 0.4

We will use simulation to create the null distribution.

# 2.
You work for a website design company and have performed an A/B test on the position of a banner on a website promoting a particular item. You selected five days at random last month and then randomly selected 200 of each sampled day’s users into group A and another 200 of that day’s users into group B. Group A continued to be shown the banner at the right hand side of the webpage (its usual position) while group B was shown the banner at the top of the page. You monitored each sampled user’s interactions with the website, in particular the ‘click through rate’ (CTR) on the banner, i.e. what proportion of sampled users clicked on the banner. You want to use the sampled data to test the hypothesis that website users overall are more likely to click on the banner if positioned at the top of the page.
-->

H0: π top(ctr) - π right(ctr) = 0
Ha: π top(ctr) - π right(ctr) > 0

We will use permutation to generate the null distribution.

# 3.
You work as an analyst for a car manufacturing company - they have specific standards they must meet for standards and regulation purposes. You have been asked to check the quality control of the manufacture of a particular car part. You have been given data on a sample of 200 parts produced over the period of a week (the sampled parts were pulled at random from the production line and measured: the factory produced a lot more than 200 parts that week). The specification of the part stipulates a width of 145mm, and the manufacturing process is said to have ‘drifted’ if the mean width of parts differs significantly from 145mm. You want to use the sampled measurements to test whether the process overall has drifted.
-->

H0: μ (width - 145) = 0
Ha: μ (width -145) ≠ 0

We will use bootstrapping to generate the null distribution.

------------------------------
1.2.2 Interpreting the results
------------------------------

1. Coffee shop problem. Significance level: 0.05, calculated p-value: 0.07

p_value (0.07) > significance level (0.05)

We fail to reject the null hypothesis. 

We don't have enough evidence to say that 40% or more of the town’s population have heard of the coffee shop.

2. Website company problem. Significance level: 0.01, p-value: 0.006

p_value (0.006) < significance level (0.01)

We reject the null hypothesis.

There is enough evidence to believe that website users overall are more likely to click on the banner if positioned at the top of the page.

3. Manufacturing company problem. Significance level: 0.05, p-value: 0.55

p_value (0.55) > significance level (0.05)

We fail to reject the null hypothesis.

There is not sufficient evidence to conclude that the process overall has drifted.