---
title: "Confidence intervals"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
library(infer)
```

```{r}
ames <- read_csv("data/ames.csv") %>% 
  clean_names()
```

```{r}
max(ames$sale_price)
min(ames$sale_price)
```

2. Sales distribution is right skewed
```{r}
# histogram of sales
ames %>% 
  ggplot(aes(x = sale_price))+
  geom_histogram(col = "white", fill = "steel blue", alpha = 0.7)
```

3. 

```{r}
# population parameter mean of sale_price
mean_sale_price_ames <- ames %>% 
  summarise(mean_sale_price = mean(sale_price))
mean_sale_price_ames
```

4. 

```{r}
sample_100 <- ames %>% 
  rep_sample_n(size = 100, reps = 1000)
```

```{r}
bootstrap_sample_100 <- sample_100 %>% 
  rep_sample_n(size = 100, replace = TRUE, reps = 1000) %>% 
  summarise(mean_sale_price =  mean(sale_price))
```

95%  CI for each bootstrap distribution:

```{r}
results_1 <- bootstrap_sample_100 %>%
  summarise(
    #mean = mean(mean_sale_price),
    lower_bound = quantile(mean_sale_price, probs = 0.025),
    upper_bound = quantile(mean_sale_price, probs = 0.975)
  )

results_1
```

