---
title: "Confidence intervals"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
library(infer)
```

```{r}
ames <- read_csv("data/ames.csv") %>% 
  clean_names()
```

```{r}
max(ames$sale_price)
min(ames$sale_price)
```

2. Sales distribution is right skewed
```{r}
# histogram of sales
ames %>% 
  ggplot(aes(x = sale_price))+
  geom_histogram(col = "white", fill = "steel blue", alpha = 0.7)
```

3. 

```{r}
# population parameter mean of sale_price
mean_sale_price_ames <- ames %>% 
  summarise(mean_sale_price = mean(sale_price))
```

4. 

```{r}
sample_100 <- ames %>% 
  rep_sample_n(size = 100, reps = 1000)
```

```{r}
bootstrap_sample_100 <- sample_100 %>% 
  rep_sample_n(size = 100, replace = TRUE, reps = 1000) %>% 
  summarise(mean_sale_price =  mean(sale_price))
```

95%  CI for each bootstrap distribution:

```{r}
results_1 <- bootstrap_sample_100 %>%
  summarise(
    #mean = mean(mean_sale_price),
    lower_bound = quantile(mean_sale_price, probs = 0.025),
    upper_bound = quantile(mean_sale_price, probs = 0.975)
  )

results_1
```

```{r}
results <- tibble()
for (sample_num in 1:1000){

  # get a new 100-observation random sample from ames
  this_sample <- ames %>%
    rep_sample_n(size = 100, reps = 1) %>%
    ungroup() %>%
    select(sale_price)
  
  # create a bootstrap distribution of mean(sale_price)
  # use 1000 reps
  this_bootstrap <- this_sample %>%
    specify(response = sale_price) %>%
    generate(reps = 1000, type = "bootstrap") %>%
    calculate(stat = "mean")

  # get 95% CI for this bootstrap distribution
  this_ci <- this_bootstrap %>%
    get_ci(level = 0.95, type = "percentile")
  
  # prepare new row for results, storing CI bounds
  this_result <- c(
    sample_num = sample_num, 
    lower = this_ci %>% 
      pull(lower_ci), 
    upper = this_ci %>%
      pull(upper_ci)
  )
  
  # add this_result to growing tibble of results
  results <- results %>%
    bind_rows(this_result)
}
```


```{r}
#results %>% 
  #mutate(popn_param_in_ci = if_else(lower > 161135.6 & upper < 204645.6, TRUE, FALSE))
```

```{r}
results %>%
  summarise(proportion_CI_containing_popn_param = mean(popn_param_in_ci))
```

